# Installs a per-user autostart entry (no admin required) so the Job Seeker
# dashboard launches at Windows logon, runs as you (so the claude/codex CLI
# login is available), and stays loopback-only.
#
# It drops a tiny .vbs launcher into the user's Startup folder. The .vbs starts
# run_dashboard.ps1 fully hidden (no console flash) via a hidden PowerShell.
#
# Usage:  powershell -ExecutionPolicy Bypass -File scripts\install_dashboard_startup.ps1 [-Port 8000]
# Remove: powershell -ExecutionPolicy Bypass -File scripts\uninstall_dashboard_startup.ps1
param(
    [int]$Port = 8000
)

$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$runner = Join-Path $root "scripts\run_dashboard.ps1"
if (-not (Test-Path $runner)) {
    throw "Launcher not found: $runner"
}

$startup = [Environment]::GetFolderPath('Startup')
$vbsPath = Join-Path $startup "JobSeekerDashboard.vbs"

# WScript.Shell.Run(cmd, 0, False): window style 0 = hidden, non-blocking.
# Inside a VBScript string literal a double quote must be written as "" (two
# quotes), so the path around $runner is wrapped in doubled quotes below.
$qq = '""'
$psCmd = "powershell.exe -NoProfile -WindowStyle Hidden -ExecutionPolicy Bypass -File ${qq}${runner}${qq} -Port $Port"
$vbs = @"
' Auto-generated by install_dashboard_startup.ps1 - launches the Job Seeker dashboard at logon.
Set sh = CreateObject("WScript.Shell")
sh.Run "$psCmd", 0, False
"@
Set-Content -Path $vbsPath -Value $vbs -Encoding ASCII

Write-Host "Installed autostart entry: $vbsPath"
Write-Host "The dashboard will start at your next logon on http://127.0.0.1:$Port/"
Write-Host "Starting it now as well..."

# Start it immediately for this session too (skip if the port is already taken).
$inUse = $null
try { $inUse = Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction SilentlyContinue } catch {}
if ($inUse) {
    Write-Host "Port $Port is already in use - assuming the dashboard is already running; not starting a second copy."
} else {
    Start-Process powershell.exe -ArgumentList "-NoProfile","-WindowStyle","Hidden","-ExecutionPolicy","Bypass","-File","$runner","-Port","$Port" -WorkingDirectory $root -WindowStyle Hidden | Out-Null
    Write-Host "Started. Give it about 10 seconds, then open http://127.0.0.1:$Port/"
}

Write-Host "Remove autostart with: powershell -ExecutionPolicy Bypass -File scripts\uninstall_dashboard_startup.ps1"
